version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nginx
    
permissions:
  - object: /home/ubuntu/nginx
    mode: 775
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: dockerStart.sh
      runas: root
