version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: /home/ubuntu/
      timeout: 15
    - name: Pulling Nginx image
      run:  docker pull nginx:latest
    - name: Running Nginx container
      run:  docker run -d --name nginx-container -p 80:80 nginx:latest
